services:
  # ------------ FRONTEND ------------
  - type: static
    name: pasos-sin-limites-frontend
    branch: main
    rootDir: frontend-auth
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://pasos-sin-limites-backend.onrender.com
